// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-TGxhJoZ5TzBsT2skzz1Vp3X5Zb-I5kA',
    appId: '1:724441797408:web:d4d06aaf01e02131b4bd45',
    messagingSenderId: '724441797408',
    projectId: 'app-control-e7b98',
    authDomain: 'app-control-e7b98.firebaseapp.com',
    databaseURL: 'https://app-control-e7b98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-control-e7b98.appspot.com',
    measurementId: 'G-QK7NKX2EB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUHCo7VkXqcrbAXAKxO-GVkBcudwmOz0M',
    appId: '1:724441797408:android:f69cc18bbebad41eb4bd45',
    messagingSenderId: '724441797408',
    projectId: 'app-control-e7b98',
    databaseURL: 'https://app-control-e7b98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-control-e7b98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4PrlR7FTqT7kKA459cOJ25itCcFdQOmY',
    appId: '1:724441797408:ios:5ac025ee6d9ba4a7b4bd45',
    messagingSenderId: '724441797408',
    projectId: 'app-control-e7b98',
    databaseURL: 'https://app-control-e7b98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-control-e7b98.appspot.com',
    iosBundleId: 'com.example.parentalctrl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4PrlR7FTqT7kKA459cOJ25itCcFdQOmY',
    appId: '1:724441797408:ios:477a1eb3c67e78e8b4bd45',
    messagingSenderId: '724441797408',
    projectId: 'app-control-e7b98',
    databaseURL: 'https://app-control-e7b98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-control-e7b98.appspot.com',
    iosBundleId: 'com.example.parentalctrl.RunnerTests',
  );
}
